name: Build stm32flash

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master

env:
  xcompile_vars: 'CC=arm-linux-musleabihf-gcc CXX=arm-linux-musleabihf-g++ INCLUDE="-I/usr/arm-linux-musleabihf/include/"'

jobs:
  build-stm32flash:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up cross-compiler
      run: |
        pwd
        wget https://musl.cc/arm-linux-musleabihf-cross.tgz
        tar -zxf arm-linux-musleabihf-cross.tgz
        sudo cp -r arm-linux-musleabihf-cross/* /usr/

    - name: Compile stm32flash
      run: |
        sudo make ${{ env.xcompile_vars }}
    
    - name: Upload stm32flash binary
      uses: actions/upload-artifact@v2
      with:
        name: stm32flash
        path: ./stm32flash

