name: Build stm32flash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
      
jobs:
  build-stm32flash:
    name: Run cross-compiler download and verification for each architecture
    strategy:
      matrix:
        arch:
           - arm-linux-musleabihf
           - aarch64-linux-musl
    
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables based on architecture
      run: |
        echo "Setting environment variables based on architecture"
        echo "xcompile_vars=CC=${{ matrix.arch }}-gcc CXX=${{ matrix.arch }}-g++ INCLUDE=-I/usr/${{ matrix.arch }}/include/" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Download musl-cross-compiler library from release
      id: musl-cross-compiler
      uses: robinraju/release-downloader@v1.8
      with:
        repository: coolitsystemsinc/cdu-lib
        latest: true
        token: ${{ secrets.ACTIONS_AUTH }}
        fileName: "${{ matrix.arch }}-cross.tgz"
        extract: false
        out-file-path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{ matrix.arch }}-cross.tgz
        sudo cp -r ./${{ matrix.arch }}-cross/* /usr/

    - name: Compile stm32flash
      run: |
        sudo make $xcompile_vars
    
    - name: Upload stm32flash binary
      uses: actions/upload-artifact@v4
      with:
        name: stm32flash${{ matrix.arch == 'aarch64-linux-musl' && '-64' || '' }}
        path: ./stm32flash

